name: Aroma CI

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Grant execute permission for gradlew
      run: chmod +x build.sh
    - name: Build with Gradle
      run : ./build.sh 
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aromainstaller
        path: out
